#
# (OS X)
#
# What is this?
#
# It's a shell script that is using sips to create all the icon files from one source icon.
#
# Stick the script in your 'www/res/icons' folder with your source icon 'my-hires-icon.png' then trigger it from Terminal.
#

SPLASH=${1}

mkdir ios
mkdir android
sips="sips"
padColor="e5e9e8"
newFile="android/screen-xhdpi-landscape.png"
cp "${SPLASH}" "${newFile}"
$sips -z 512 512 --padToHeightWidth 1280 720 --padColor $padColor "${newFile}"
newFile="android/screen-hdpi-portrait.png"
cp "${SPLASH}" "${newFile}"
$sips -z 256 256 --padToHeightWidth 480 800 --padColor $padColor "${newFile}"
newFile="android/screen-ldpi-landscape.png"
cp "${SPLASH}" "${newFile}"
$sips -z 128 128 --padToHeightWidth 320 200 --padColor $padColor "${newFile}"
newFile="android/screen-xhdpi-portrait.png"
cp "${SPLASH}" "${newFile}"
$sips -z 512 512 --padToHeightWidth 720 1280 --padColor $padColor "${newFile}"
newFile="android/screen-mdpi-portrait.png"
cp "${SPLASH}" "${newFile}"
$sips -z 256 256 --padToHeightWidth 320 480 --padColor $padColor "${newFile}"
newFile="android/screen-mdpi-landscape.png"
cp "${SPLASH}" "${newFile}"
$sips -z 256 256 --padToHeightWidth 480 320 --padColor $padColor "${newFile}"
newFile="android/screen-ldpi-portrait.png"
cp "${SPLASH}" "${newFile}"
$sips -z 128 128 --padToHeightWidth 200 320 --padColor $padColor "${newFile}"
newFile="android/screen-hdpi-landscape.png"
cp "${SPLASH}" "${newFile}"
$sips -z 256 256 --padToHeightWidth 800 480 --padColor $padColor "${newFile}"
#newFile="bada/screen-portrait.png"
#cp "${SPLASH}" "${newFile}"
#$sips -z 256 256 --padToHeightWidth 480 800 --padColor $padColor "${newFile}"
#newFile="bada/screen-type3.png"
#cp "${SPLASH}" "${newFile}"
#$sips -z 128 128 --padToHeightWidth 320 480 --padColor $padColor "${newFile}"
#newFile="bada/screen-type4.png"
#cp "${SPLASH}" "${newFile}"
#$sips -z 256 256 --padToHeightWidth 480 800 --padColor $padColor "${newFile}"
#newFile="bada/screen-type5.png"
#cp "${SPLASH}" "${newFile}"
#$sips -z 128 128 --padToHeightWidth 240 400 --padColor $padColor "${newFile}"
#newFile="bada/screen-type6.png"
#cp "${SPLASH}" "${newFile}"
#$sips -z 256 256 --padToHeightWidth 480 800 --padColor $padColor "${newFile}"
#newFile="bada/screen-type-225.png"
#cp "${SPLASH}" "${newFile}"
#$sips -z 128 128 --padToHeightWidth 225 225 --padColor $padColor "${newFile}"
newFile="ios/screen-iphone-portrait.png"
cp "${SPLASH}" "${newFile}"
$sips -z 256 256 --padToHeightWidth 320 480 --padColor $padColor "${newFile}"
newFile="ios/screen-iphone-landscape-2x.png"
cp "${SPLASH}" "${newFile}"
$sips -z 256 256 --padToHeightWidth 960 640 --padColor $padColor "${newFile}"
newFile="ios/screen-iphone-landscape.png"
cp "${SPLASH}" "${newFile}"
$sips -z 256 256 --padToHeightWidth 480 320 --padColor $padColor "${newFile}"
newFile="ios/screen-ipad-portrait.png"
cp "${SPLASH}" "${newFile}"
$sips -z 512 512 --padToHeightWidth 768 1004 --padColor $padColor "${newFile}"
newFile="ios/screen-ipad-portrait-2x.png"
cp "${SPLASH}" "${newFile}"
$sips -z 1024 1024 --padToHeightWidth 1536 2008 --padColor $padColor "${newFile}"
newFile="ios/screen-ipad-landscape.png"
cp "${SPLASH}" "${newFile}"
$sips -z 512 512 --padToHeightWidth 1024 783 --padColor $padColor "${newFile}"
newFile="ios/screen-iphone-portrait-2x.png"
cp "${SPLASH}" "${newFile}"
$sips -z 256 256 --padToHeightWidth 640 960 --padColor $padColor "${newFile}"
newFile="ios/screen-ipad-landscape-2x.png"
cp "${SPLASH}" "${newFile}"
$sips -z 1024 1024 --padToHeightWidth 2008 1536 --padColor $padColor "${newFile}"
#newFile="webos/screen-64.png"
#cp "${SPLASH}" "${newFile}"
#$sips -z 64 64 webos/"${newFile}"
#newFile="windows-phone/screen-portrait.jpg"
#cp "${SPLASH}" windows-phone/"${newFile}"
#$sips -z 256 256 --padToHeightWidth 480 800 --padColor $padColor "${newFile}"
